---
title: "Prior parameter choices"
author: "Joël Koelewijn"
date: "2023-05-02"
output: html_document
---
All the priors with the values and type of distribution used.

"Run 4 - BDMM-Prime", 21 species, BDMM', strict clock, no age boundaries:
Prior:	                Type:	          Mean:	    Upper:	Start:	 Lower:                 
Birth rate	            Exponential	    1			
Clock rate	            Exponential	    1			
Death rate	            Exponential	    1			
Gamma shape	            Exponential	    1			
Origin BDMM'	          Uniform		                150	    70	      35
Proportion Invariant	  Uniform		                1	      0	        0
Sampling rate	          Exponential	    0.1			
Removal prob.	          0				

"Run 5 - 21 species - age uncertainty - Relaxed clock", 21 species, BDMM', Relaxed clock, added age boundaries:
Clock model: Relaxed clock exponential. number of discrete rates = 0

Prior:	                Type:	          Mean:	    Upper:	Start:	 Lower:                 
Birth rate	            Exponential	    1			
Death rate	            Exponential	    1			
Gamma shape	            Exponential	    1			
Origin BDMM'	          Uniform		                150	    70	      30
Proportion Invariant	  Uniform		                1	      0	        0
Sampling rate	          Exponential	    0.1			
Removal prob.	          0		
ucedMean                Exponential     1